### PR TITLE
Feature/sending texts

### PR DESCRIPTION
**Pull request by iancj97**
Added the ability to send texts

### CODE REVIEW

**Review by bbbbbbbbhh — APPROVED** [review]

**Comment by bbbbbbbbhh** [comment]
Merge latest changes from develop

**Comment by iancj97** [comment]
@benhylak

**Comment by iancj97** [comment]
@benhylak @bhylak You have to check this off even though it's almost no code.

**Review by benhylak — COMMENTED** [review]
Assuming it works, not sure how to test yet

**Comment by iancj97** [comment]
Yes it works. Test it by running the test case with your phone number.

**Comment by iancj97** [comment]
Currently, whenever Travis compiles I get a text

**Comment by benhylak** [comment]
okay! wanna take that out b4 merge?

**Comment by iancj97** [comment]
Nope, it's intended behavior.

**Pull request merged**
