### PR TITLE
Fixed all node offsets

### PR DESCRIPTION
**Pull request by pjpolley**
Fixed node saving and loading in all situations.

### CODE REVIEW

**Review by benhylak — COMMENTED** [review]
Great job Patrick!

**Comment by pjpolley** [comment]
The problem was in the DragIcon class function relocateToPoint (Point2D p). Whenever this was called the node positions were incremented by half their width and height, which was causing the nodes to appear to inch down the screen as scene transitions were called (as whenever the nodes were loaded relocateToPoint was called.

**Comment by pjpolley** [comment]
#45 Fixed issue by changing class function relocateToPoint (Point2D p). The function was incrementing the node positions by their width and height whenever the nodes were rendered on screen.

**Review by benhylak — APPROVED** [review]
Works!

**Pull request merged**
