### PR TITLE
Moved PathfindingTest to domain, removed outdated pathtest

### PR DESCRIPTION
**Pull request by iancj97**
Updating location of tests

### CODE REVIEW

**Comment by iancj97** [comment]
Making comment

**Comment by iancj97** [comment]
@bhylak Look good? The tests have been moved from one directory to another, with some small (adding semicolon) changes.

**Comment by benhylak** [comment]
Move test case class back to test/java folder

 symbol: class TestCase
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:29: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:119: error: cannot find symbol
        assertEquals(nodeA, nodeA);
        ^
  symbol:   method assertEquals(MapNode,MapNode)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:120: error: cannot find symbol
        assertEquals(nodeB, nodeB);
        ^
  symbol:   method assertEquals(MapNode,MapNode)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:121: error: cannot find symbol
        assertNotSame(nodeA, nodeB);
        ^
  symbol:   method assertNotSame(MapNode,MapNode)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:136: error: cannot find symbol
        assertTrue(manPathValid.isValidPath());
        ^
  symbol:   method assertTrue(boolean)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:137: error: cannot find symbol
        assertFalse(manPathInvalid.isValidPath());
        ^
  symbol:   method assertFalse(boolean)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:144: error: cannot find symbol
            fail("Failed to notice no possible path");
            ^
  symbol:   method fail(String)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:146: error: cannot find symbol
            assertTrue(e instanceof PathFindingNoPathException);
            ^
  symbol:   method assertTrue(boolean)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:150: error: cannot find symbol
            fail("Failed to notice no possible path");
            ^
  symbol:   method fail(String)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:152: error: cannot find symbol
            assertTrue(e instanceof PathFindingNoPathException);
            ^
  symbol:   method assertTrue(boolean)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:164: error: cannot find symbol
            assertTrue(p1.equals(p2));
            ^
  symbol:   method assertTrue(boolean)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:165: error: cannot find symbol
            assertTrue(p2.equals(p1));
            ^
  symbol:   method assertTrue(boolean)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:166: error: cannot find symbol
            assertFalse(p1.equals(p3));
            ^
  symbol:   method assertFalse(boolean)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:167: error: cannot find symbol
            assertFalse(p3.equals(p1));
            ^
  symbol:   method assertFalse(boolean)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:168: error: cannot find symbol
            assertFalse(p4.equals(p5));
            ^
  symbol:   method assertFalse(boolean)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:169: error: cannot find symbol
            assertFalse(p5.equals(p4));
            ^
  symbol:   method assertFalse(boolean)
  location: class PathFindingTest
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/Domain/Navigation/PathFindingTest.java:170: error: cannot find symbol
            assertFalse(p3.equals(p5));

**Comment by iancj97** [comment]
If the probem is errors, that has to do with how it's run. Update the run config in upper right to new location.

**Comment by benhylak** [comment]
@iancj97 it should build without setting anything in intellij. It should build with Travis.. Thats the point.

**Comment by iancj97** [comment]
@bhylak How do I go about fixing travis?

edit: I see it in gradle

**Comment by benhylak** [comment]
Better: 

/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/test/java/PathFindingTest.java:112: error: unreported exception Exception; must be caught or declared to be thrown
        myBuilding.addFloor(floor1);
                           ^
/home/travis/build/CS3733TeamBeta/Faulkner.Kiosk/src/test/java/PathFindingTest.java:113: error: unreported exception Exception; must be caught or declared to be thrown
        myBuilding.addFloor(floor2);

**Comment by iancj97** [comment]
Why is travis thinking adding a floor to a building throws an exception?

**Comment by iancj97** [comment]
Now travis can't find Junit. Does something need to be done in gradle to have travis recognize junit? @bhylak

**Comment by benhylak** [comment]
@iancj97 Ian, I get the same errors on my computer. Travis isn't special, just think of it as a blank computer without any previous settings.

**Comment by iancj97** [comment]
Why would only my computer recognize import ` junit.framework.TestCase;`? @bhylak

**Comment by iancj97** [comment]
I messed with build.gradle file and added a `    compile 'junit.framework.TestCase'` in the dependencies area. Seems to not have worked.

**Comment by benhylak** [comment]
YAYYYYY @iancj97  GOOD JOB!

**Pull request merged**
